options {
    listen-on port 53 { 192.168.50.10; };
    listen-on-v6 port 53 { ::1; };

    directory         "/var/cache/bind";
    dump-file         "/var/cache/bind/cache_dump.db";
    statistics-file   "/var/cache/bind/named_stats.txt";
    memstatistics-file "/var/cache/bind/named_mem_stats.txt";

    recursion yes;
    allow-query     { any; };
    allow-transfer  { any; };

    dnssec-validation auto;

    bindkeys-file "/etc/bind/bind.keys";
    managed-keys-directory "/var/cache/bind/dynamic";
    pid-file "/run/named/named.pid";
    session-keyfile "/run/named/session.key";
};

logging {
    channel default_debug {
        file "data/named.run";
        severity dynamic;
    };
};

key "rndc-key" {
    algorithm hmac-md5;
    secret "GrtiE9kz16GK+OKKU/qJvQ==";
};

controls {
    inet 192.168.50.10 allow { 192.168.50.15; 192.168.50.16; } keys { "rndc-key"; };
};

key "client-key" {
    algorithm hmac-sha256;
    secret "IQg171Ht4mdGYcjjYKhI9gSc1fhoxzHZB+h2NMtyZWY=";
};

key "client2-key" {
    algorithm hmac-sha256;
    secret "m7r7SpZ9KBcA4kOl1JHQQnUiIlpQA1IJ9xkBHwdRAHc=";
};

include "/etc/bind/named.zonetransfer.key";

server 192.168.50.11 {
    keys { "zonetransfer.key"; };
};

acl client { !key client2-key; key client-key; 192.168.50.15; };
acl client2 { !key client-key; key client2-key; 192.168.50.16; };

view "client" {
    match-clients { client; };

    zone "dns.lab" {
        type master;
        file "/etc/bind/named.dns.lab.client";
        also-notify { 192.168.50.11 key client-key; };
    };

    zone "newdns.lab" {
        type master;
        file "/etc/bind/named.newdns.lab";
        also-notify { 192.168.50.11 key client-key; };
    };
};

view "client2" {
    match-clients { client2; };

    zone "dns.lab" {
        type master;
        file "/etc/bind/named.dns.lab";
        also-notify { 192.168.50.11 key client2-key; };
    };

    zone "50.168.192.in-addr.arpa" {
        type master;
        file "/etc/bind/named.dns.lab.rev";
        also-notify { 192.168.50.11 key client2-key; };
    };
};

view "default" {
    match-clients { any; };

    zone "." IN {
        type hint;
        file "/etc/bind/db.root";
    };

    include "/etc/bind/named.conf.default-zones";

    zone "dns.lab" {
        type master;
        allow-transfer { key "zonetransfer.key"; };
        file "/etc/bind/named.dns.lab";
    };

    zone "50.168.192.in-addr.arpa" {
        type master;
        allow-transfer { key "zonetransfer.key"; };
        file "/etc/bind/named.dns.lab.rev";
    };

    zone "ddns.lab" {
        type master;
        allow-transfer { key "zonetransfer.key"; };
        allow-update { key "zonetransfer.key"; };
        file "/etc/bind/named.ddns.lab";
    };

    zone "newdns.lab" {
        type master;
        allow-transfer { key "zonetransfer.key"; };
        file "/etc/bind/named.newdns.lab";
    };
};
